CREATE TABLE `comentario` (
  `ID` int(5) NOT NULL,
  `NOME` varchar(255) NOT NULL,
  `DESCRICAO` text NOT NULL,
  `GUIA` int(5) NOT NULL,
  `ATIVO` int(1) NOT NULL DEFAULT '0',
  `DATA` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE `comentario`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `comentario`
  MODIFY `ID` int(5) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;